version: '2'
services:
  web:
    volumes:
      - ~/cache:/cache
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ''
  selenium:
    image: selenium/standalone-chrome-debug:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - 5900:5900
    expose:
      - 4444
